export const Data = {
    "Andalucía": [
      "Almería",
      "Cádiz",
      "Córdoba",
      "Granada",
      "Huelva",
      "Jaén",
      "Málaga",
      "Sevilla",
      "Marbella",
    ],
    "Aragón": [
      "Huesca",
      "Teruel",
      "Zaragoza"
    ],
    "Asturias": [
      "Avilés",
      "Gijón",
      "Oviedo",

    ],
    "Baleares": [
      "Alaior",
      "Alcúdia",
      "Algaida",
      "Andratx",
      "Ariany",
      "Artà",
      "Banyalbufar",
      "Binissalem",
      "Búger",
      "Bunyola",
      "Calvià",
      "Campanet",
      " Campos",
      "Capdepera",
      "Castell (Es)",
      "Ciutadella de Menorca",
      "Consell",
      "Costitx",
      "Deyá",
      "Eivissa",
      "Es Castell",
      "Escorca",
      "Esporles",
      "Estellencs",
      "Felanitx",
      "Ferreries",
      "Formentera",
      "Fornalutx",
      "Inca",
      "Lloret de Vistalegre",
      "Lloseta",
      "Llubí",
      "Llucmajor",
      "Manacor",
      "Mancor de la Vall",
      "Maó",
      "Maria de la Salut",
      "Marratxí",
      "Mercadal (Es)",
      "Migjorn Gran (Es)",
      "Montuïri",
      "Muro",
      "Palma",
      "Petra",
      "Pobla (Sa)",
      "Pollença",
      "Porreres",
      "Puigpunyent",
      "Salines (Ses)",
      "Sant Antoni de Portmany",
      "Sant Joan",
      "Sant Joan de Labritja",
      "Sant Josep de sa Talaia",
      "Sant Llorenç des Cardassar",
      "Sant Lluís",
      "Santa Eugènia",
      "Santa Eulalia del Río",
      "Santa Margalida",
      "Santa María del Camí",
      "Santanyí",
      "Selva",
      "Sencelles",
      "Sineu",
      "Son Servera",
      "Valldemossa",
      "Vilafranca de Bonany"
    ],
    "Canarias": [
      "Agaete",
      "Agüimes",
      "Aldea de San Nicolás (La)",
      "Antigua",
      "Arrecife",
      "Artenara",
      "Arucas",
      "Betancuria",
      "Breña Alta",
      "Breña Baja",
      "Frontera",
      "Garachico",
      "Granadilla de Abona",
      "Guía de Isora",
      "Haría",
      "Hermigua",
      "Icod de los Vinos",
      "Lanzarote",
      "La Oliva",
      "Las Palmas de Gran Canaria",
      "Los Llanos de Aridane",
      "Mogán",
      "Moya",
      "Pájara",
      "Puntagorda",
      "Puntallana",
      "San Bartolomé",
      "San Bartolomé de Tirajana",
      "San Cristóbal de La Laguna",
      "San Juan de la Rambla",
      "San Miguel de Abona",
      "San Sebastián de La Gomera",
      "Santa Brígida",
      "Santa Cruz de La Palma",
      "Santa Cruz de Tenerife",
      "Santa Lucía de Tirajana",
      "Santa María de Guía de Gran Canaria",
      "Tazacorte",
      "Teguise",
      "Tijarafe",
      "Valle Gran Rey",
      "Vallehermoso",
      "Valverde",
      "Valsequillo de Gran Canaria",
      "Villa de Mazo"
      ],
      "Cantabria": [
      "Camargo",
      "Castro-Urdiales",
      "El Astillero",
      "Piélagos",
      "Santander",
      "Torrelavega"
      ],
      "Castilla-La Mancha": [
      "Albacete",
      "Ciudad Real",
      "Cuenca",
      "Guadalajara",
      "Toledo"
      ],
      "Castilla y León": [
      "Ávila",
      "Burgos",
      "León",
      "Palencia",
      "Salamanca",
      "Segovia",
      "Soria",
      "Valladolid",
      "Zamora"
      ],
      "Cataluña": [
      "Barcelona",
      "Girona",
      "Lleida",
      "Tarragona"
      ],
      "Ceuta": [
      "Ceuta"
      ],
      "Comunidad de Madrid": [
      "Alcalá de Henares",
      "Aranjuez",
      "Alcobendas",
      "Alcorcón",
      "Arroyomolinos",
      "Boadilla del Monte",
      "Chinchón",
      "Ciempozuelos",
      "Collado Villalba",
      "Colmenar Viejo",
      "Coslada",
      "Fuenlabrada",
      "Getafe",
      "Leganés",
      "Madrid",
      "Majadahonda",
      "Móstoles",
      "Paracuellos de Jarama",
      "Parla",
      "Pinto",
      "Pozuelo de Alarcón",
      "Rivas-Vaciamadrid",
      "San Fernando de Henares",
      "San Lorenzo de El Escorial",
      "San Martín de Valdeiglesias",
      "San Sebastián de los Reyes",
      "Torrejón de Ardoz",
      "Torrelodones",
      "Tres Cantos",
      "Valdemoro"
      ],
      "Comunidad Foral de Navarra": [
      "Pamplona"
      ],
      "Comunidad Valenciana": [
      "Alicante",
      "Castellón",
      "Valencia"
      ],
      "Extremadura": [
      "Badajoz",
      "Cáceres",
      "Mérida",
      "Plasencia",
      
      ],
      "Galicia": [
      "A Coruña",
      "Lugo",
      "Ourense",
      "Pontevedra"
      ],
      "La Rioja": [
      "Logroño"
      ],
      "Melilla": [
      "Melilla",
     
    ],
    "País Vasco": [
    "Bilbao",
    "Donostia-San Sebastián",
    "Vitoria-Gasteiz"
    ],
    "Región de Murcia": [
    "Cartagena",
    "Lorca",
    "Murcia"
    ]
    }
  